/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema_de_elecciones_happy_land;

import java.awt.Color;
import javax.swing.JOptionPane;
import java.awt.event.*;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPasswordField;
import javax.swing.Timer;

/**
 *
 * @author APeña
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    //Variables globales
    public  static int contador_partido_1=0;
    public static int contador_partido_2=0;
    public static int contador_partido_3=0;
    public static int contador_partido_4=0;
    
    
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);
       // setExtendedState(MAXIMIXED_BOTH);
        limpiar_resultados();
        deshabilitar_botones();
        ocultar_botones();
        ocultar_label();
        this.btn_votar.setEnabled(true);
        this.btn_votar.setVisible(true);
        this.btn_mostrar_resultados.setEnabled(false);
        this.btn_mostrar_resultados.setVisible(false);
        this.btn_salir.setEnabled(true);
        //guardar_en_archivo();
        //deshabilitar_resultados();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_partido_1 = new javax.swing.JButton();
        btn_partido_2 = new javax.swing.JButton();
        btn_partido_3 = new javax.swing.JButton();
        btn_mostrar_resultados = new javax.swing.JButton();
        lbl_partido_1 = new javax.swing.JLabel();
        lbl_partido_2 = new javax.swing.JLabel();
        lbl_partido_3 = new javax.swing.JLabel();
        btn_votar = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_partido_4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lbl_partido_4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Elecciones Happy Land School 2020");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("FROILÁN TURCIOS");
        jLabel1.setToolTipText("");

        btn_partido_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Logo Froilan Turcios.png"))); // NOI18N
        btn_partido_1.setName("btn_partido_2"); // NOI18N
        btn_partido_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_partido_1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_partido_1MouseExited(evt);
            }
        });
        btn_partido_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_partido_1_ActionPerformed(evt);
            }
        });

        btn_partido_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Logo Marco Aurelio Soto.png"))); // NOI18N
        btn_partido_2.setName("btn_partido_3"); // NOI18N
        btn_partido_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_partido_2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_partido_2MouseExited(evt);
            }
        });
        btn_partido_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_partido_2_ActionPerformed(evt);
            }
        });

        btn_partido_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Logo movimiento ciudadano.png"))); // NOI18N
        btn_partido_3.setToolTipText("");
        btn_partido_3.setName("btn_partido_4"); // NOI18N
        btn_partido_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_partido_3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_partido_3MouseExited(evt);
            }
        });
        btn_partido_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_partido_3_ActionPerformed(evt);
            }
        });

        btn_mostrar_resultados.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_mostrar_resultados.setText("MOSTRAR RESULTADOS");
        btn_mostrar_resultados.setToolTipText("");
        btn_mostrar_resultados.setName("btn_resultados"); // NOI18N
        btn_mostrar_resultados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_mostrar_resultadosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_mostrar_resultadosMouseExited(evt);
            }
        });
        btn_mostrar_resultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mostrar_resultados_ActionPerformed(evt);
            }
        });

        lbl_partido_1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lbl_partido_1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lbl_partido_1.setEnabled(false);
        lbl_partido_1.setName("lbl_partido_1"); // NOI18N

        lbl_partido_2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lbl_partido_2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lbl_partido_2.setEnabled(false);
        lbl_partido_2.setName("lbl_partido_2"); // NOI18N

        lbl_partido_3.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lbl_partido_3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lbl_partido_3.setEnabled(false);
        lbl_partido_3.setName("lbl_partido_1"); // NOI18N

        btn_votar.setBackground(new java.awt.Color(204, 255, 204));
        btn_votar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/btn verde.png"))); // NOI18N
        btn_votar.setName("btn_votar"); // NOI18N
        btn_votar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_votarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_votarMouseExited(evt);
            }
        });
        btn_votar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_votar_ActionPerformed(evt);
            }
        });

        btn_salir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_salir.setToolTipText("");
        btn_salir.setActionCommand("btn_salir");
        btn_salir.setLabel("SALIR");
        btn_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_salirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_salirMouseExited(evt);
            }
        });
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salir_ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("MARCO AURELIO SOTO");
        jLabel2.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("CIUDADANO");
        jLabel3.setToolTipText("");

        btn_partido_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/btn salir.png"))); // NOI18N
        btn_partido_4.setToolTipText("");
        btn_partido_4.setName("btn_partido_4"); // NOI18N
        btn_partido_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_partido_4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_partido_4MouseExited(evt);
            }
        });
        btn_partido_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_partido_4_ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("NULO");
        jLabel4.setToolTipText("");

        lbl_partido_4.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lbl_partido_4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lbl_partido_4.setEnabled(false);
        lbl_partido_4.setName("lbl_partido_1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_votar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbl_partido_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_partido_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(35, 35, 35)))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btn_partido_2, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(46, 46, 46)
                                                .addComponent(jLabel2)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(130, 130, 130)
                                                .addComponent(jLabel3)
                                                .addGap(273, 273, 273)
                                                .addComponent(jLabel4))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(45, 45, 45)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(btn_partido_3, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lbl_partido_3, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(48, 48, 48)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(btn_partido_4, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lbl_partido_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                                    .addComponent(lbl_partido_2, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_mostrar_resultados, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_partido_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_partido_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_partido_3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_partido_4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbl_partido_2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_partido_1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_partido_3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_partido_4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_votar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_mostrar_resultados, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(btn_salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(8, 8, 8))
        );

        btn_salir.getAccessibleContext().setAccessibleDescription("btn_salir");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_partido_1_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_partido_1_ActionPerformed
        contador_partido_1=contador_partido_1 + 1;
        deshabilitar_botones();
        despues_votar();
    }//GEN-LAST:event_btn_partido_1_ActionPerformed

    private void btn_partido_2_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_partido_2_ActionPerformed
        // TODO add your handling code here:
         contador_partido_2=contador_partido_2 + 1;
         despues_votar();
         
    }//GEN-LAST:event_btn_partido_2_ActionPerformed

    private void btn_partido_3_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_partido_3_ActionPerformed
        // TODO add your handling code here:
        contador_partido_3=contador_partido_3 + 1;
        despues_votar();
        
    }//GEN-LAST:event_btn_partido_3_ActionPerformed

    private void btn_votar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_votar_ActionPerformed
        // TODO add your handling code here:
        //Espera en milisegundos en el sistema
        ver_botones();
        ver_label();
        habilitar_botones();
        this.btn_votar.setEnabled(false);
        this.btn_votar.setVisible(false);
        this.btn_mostrar_resultados.setEnabled(true);
        this.btn_mostrar_resultados.setVisible(true);
       
         
    }//GEN-LAST:event_btn_votar_ActionPerformed

    private void btn_mostrar_resultados_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mostrar_resultados_ActionPerformed
        // TODO add your handling code here:
        //String clave=String.valueOf(JOptionPane.showInputDialog("Ingrese la clave para mostrar los resultados:"));
        //if( "123".equals(clave)){
        //    habilitar_resultados();
        //}
        String clave;
        JPasswordField contraseña = new JPasswordField();
        if(JOptionPane.showConfirmDialog(null, contraseña, "Ingrese la clave para mostrar los resultados: ", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION){
            clave = new String(contraseña.getPassword());
            if( "123".equals(clave)){
                ver_botones();
                ver_label();
                habilitar_resultados();
              }
        }
        
    }//GEN-LAST:event_btn_mostrar_resultados_ActionPerformed

    private void btn_salir_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salir_ActionPerformed
        // TODO add your handling code here:
        //String clave=String.valueOf(JOptionPane.showInputDialog("Ingrese la clave para salir:"));
        // Haces la comprobación de la contraseña
        //if( "123".equals(clave)){
        //    System.exit(0);
        //}
        String clave;
        JPasswordField contraseña = new JPasswordField();
        if(JOptionPane.showConfirmDialog(null, contraseña, "Ingrese la clave para salir: ", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION){
            clave = new String(contraseña.getPassword());
            if( "123".equals(clave)){
                System.exit(0);
                }
        }
        
        
    }//GEN-LAST:event_btn_salir_ActionPerformed

    
    
    //Clic al pasar sobre los botones
    private void btn_partido_1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_partido_1MouseEntered
        // TODO add your handling code here:
        this.btn_partido_1.setBackground(Color.green);
        
    }//GEN-LAST:event_btn_partido_1MouseEntered

    private void btn_partido_2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_partido_2MouseEntered
        // TODO add your handling code here:
        this.btn_partido_2.setBackground(Color.green);
    }//GEN-LAST:event_btn_partido_2MouseEntered

    
    
    
    
    
       //Clic al salir sobre los botones
    private void btn_partido_1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_partido_1MouseExited
        // TODO add your handling code here:
        this.btn_partido_1.setBackground(new Color(240,240,240));
     
    }//GEN-LAST:event_btn_partido_1MouseExited

    private void btn_partido_2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_partido_2MouseExited
        // TODO add your handling code here:
        this.btn_partido_2.setBackground(new Color(240,240,240));
    }//GEN-LAST:event_btn_partido_2MouseExited

    private void btn_partido_3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_partido_3MouseExited
        // TODO add your handling code here:
        this.btn_partido_3.setBackground(new Color(240,240,240));
    }//GEN-LAST:event_btn_partido_3MouseExited

    private void btn_partido_3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_partido_3MouseEntered
        // TODO add your handling code here:
        this.btn_partido_3.setBackground(Color.green);
    }//GEN-LAST:event_btn_partido_3MouseEntered

    private void btn_votarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_votarMouseEntered
        // TODO add your handling code here:
        this.btn_votar.setBackground(Color.green);
    }//GEN-LAST:event_btn_votarMouseEntered

    private void btn_votarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_votarMouseExited
        // TODO add your handling code here:
        this.btn_votar.setBackground(new Color(240,240,240));
    }//GEN-LAST:event_btn_votarMouseExited

    private void btn_partido_4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_partido_4MouseEntered
        // TODO add your handling code here:
        this.btn_partido_4.setBackground(Color.green);
    }//GEN-LAST:event_btn_partido_4MouseEntered

    private void btn_partido_4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_partido_4MouseExited
        // TODO add your handling code here:
         this.btn_partido_4.setBackground(new Color(240,240,240));
    }//GEN-LAST:event_btn_partido_4MouseExited

    private void btn_partido_4_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_partido_4_ActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:
        contador_partido_4=contador_partido_4 + 1;
        despues_votar();
    }//GEN-LAST:event_btn_partido_4_ActionPerformed

    private void btn_mostrar_resultadosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mostrar_resultadosMouseEntered
        // TODO add your handling code here:
        this.btn_mostrar_resultados.setBackground(Color.green);
    }//GEN-LAST:event_btn_mostrar_resultadosMouseEntered

    private void btn_mostrar_resultadosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mostrar_resultadosMouseExited
        // TODO add your handling code here:
        this.btn_mostrar_resultados.setBackground(new Color(240,240,240));
    }//GEN-LAST:event_btn_mostrar_resultadosMouseExited

    private void btn_salirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salirMouseEntered
        // TODO add your handling code here:
        this.btn_salir.setBackground(Color.green);
        
    }//GEN-LAST:event_btn_salirMouseEntered

    private void btn_salirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salirMouseExited
        // TODO add your handling code here:
        this.btn_salir.setBackground(new Color(240,240,240));
    }//GEN-LAST:event_btn_salirMouseExited

    

    
    
    
    
    
    
    //Funciones especiales
    private void esperar(){
            try {
        Thread.sleep(30000); //1000 son un segundo, dejé 10 seg= 10000, tengo que poner 30000
        } catch (InterruptedException ex) {
         Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
         }
    }
    private void muestra_mensaje(){
    
    JOptionPane.showMessageDialog(null,"USTED YA VOTO","F  E  L  I  C  I  D  A  D  E S",JOptionPane.OK_OPTION);
    
    
    }
    
    private void despues_votar(){
        deshabilitar_botones();
        ocultar_botones();
        ocultar_label();
        //this.lbl_partido_3.setText(Integer.toString(contador_partido_3));
        guardar_en_archivo();
        deshabilitar_resultados();
        muestra_mensaje();
        esperar();
        this.btn_votar.setEnabled(true); 
        this.btn_votar.setVisible(true);
        this.btn_mostrar_resultados.setEnabled(true);
        this.btn_mostrar_resultados.setVisible(true); 
        this.btn_salir.setEnabled(true);
        this.btn_salir.setVisible(true);
        

        //setLocationRelativeTo(null);
    
    }
    
    
    private void habilitar_resultados(){
    this.lbl_partido_1.setVisible(true);
    this.lbl_partido_1.setText(Integer.toString(contador_partido_1));
    this.lbl_partido_2.setVisible(true);
    this.lbl_partido_2.setText(Integer.toString(contador_partido_2));
    this.lbl_partido_3.setVisible(true);
    this.lbl_partido_3.setText(Integer.toString(contador_partido_3));
    this.lbl_partido_4.setVisible(true);
    this.lbl_partido_4.setText(Integer.toString(contador_partido_4));
    }
    
    private void deshabilitar_resultados(){
    this.lbl_partido_1.setVisible(false);
    this.lbl_partido_2.setVisible(false);
    this.lbl_partido_3.setVisible(false);
    this.lbl_partido_4.setVisible(false);
    }
    
    private void limpiar_resultados(){
    this.lbl_partido_1.setText("");
    this.lbl_partido_2.setText("");
    this.lbl_partido_3.setText("");
    this.lbl_partido_4.setText("");
    }
    
    private void habilitar_botones(){
         
    this.btn_partido_1.setEnabled(true);
    this.btn_partido_2.setEnabled(true);
    this.btn_partido_3.setEnabled(true);
    this.btn_partido_4.setEnabled(true);
    this.btn_mostrar_resultados.setEnabled(true);
    this.btn_salir.setEnabled(true);
    }
    
    private void deshabilitar_botones(){
    this.btn_votar.setEnabled(false);    
    this.btn_partido_1.setEnabled(false);
    this.btn_partido_2.setEnabled(false);
    this.btn_partido_3.setEnabled(false);
    this.btn_partido_4.setEnabled(false);
    this.btn_mostrar_resultados.setEnabled(false);
    this.btn_salir.setEnabled(false);
    }
    
    private void ver_botones(){
    this.btn_partido_1.setVisible(true);
    this.btn_partido_2.setVisible(true);
    this.btn_partido_3.setVisible(true);
    this.btn_partido_4.setVisible(true);
    }
    
    private void ocultar_botones(){
    this.btn_partido_1.setVisible(false);
    this.btn_partido_2.setVisible(false);
    this.btn_partido_3.setVisible(false);
    this.btn_partido_4.setVisible(false);
    }
    
    
    private void ver_label(){
   this.jLabel1.setVisible(true);
   this.jLabel2.setVisible(true);
   this.jLabel3.setVisible(true);
   this.jLabel4.setVisible(true);
    }
    
   private void ocultar_label(){
   this.jLabel1.setVisible(false);
   this.jLabel2.setVisible(false);
   this.jLabel3.setVisible(false);
   this.jLabel4.setVisible(false);
    }
    
    private void guardar_en_archivo(){
        
        FileWriter fichero = null;
        PrintWriter pw = null;
        try
        {
            fichero = new FileWriter("C:\\\\SE HLS 2022\\\\Back_up.txt");
            pw = new PrintWriter(fichero);

                pw.println("RESULTADOS DE ELECCIONES 2022: ");
                pw.println("Froilan Turcios(Partido 1): " + contador_partido_1);
                pw.println("Marco Aurelio Soto(Partido 2): " + contador_partido_2);
                pw.println("Ciudadano(Partido 3): " + contador_partido_3);
                pw.println("VOTOS NULOS: " + contador_partido_4);

        } catch (Exception e) {
            e.printStackTrace();
        } finally {
           try {
           // Nuevamente aprovechamos el finally para 
           // asegurarnos que se cierra el fichero.
           if (null != fichero)
              fichero.close();
           } catch (Exception e2) {
              e2.printStackTrace();
           }
        }
        
        
    }
    
    private void crear_carpeta(){
    
    //File directorio = new File("C:\\SE HLS 2022");
    
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
       
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
                
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_mostrar_resultados;
    private javax.swing.JButton btn_partido_1;
    private javax.swing.JButton btn_partido_2;
    private javax.swing.JButton btn_partido_3;
    private javax.swing.JButton btn_partido_4;
    private javax.swing.JButton btn_salir;
    private javax.swing.JButton btn_votar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbl_partido_1;
    private javax.swing.JLabel lbl_partido_2;
    private javax.swing.JLabel lbl_partido_3;
    private javax.swing.JLabel lbl_partido_4;
    // End of variables declaration//GEN-END:variables
}
